version: "3.5"
services:
  samba:
    image: joebiellik/samba-server
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - /Volumes/PS2:/mnt/ps2

    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"

    environment:
      - USERNAME=joao
      - PASSWORD=samba
